plugins {
	kotlin("jvm") version "2.3.21"
	kotlin("plugin.spring") version "2.3.21"
	id("org.springframework.boot") version "4.1.0"
	id("io.spring.dependency-management") version "1.1.7"
	id("org.graalvm.buildtools.native") version "1.1.3"
}

group = "id.archmage"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-webmvc")
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("org.postgresql:postgresql")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("tools.jackson.module:jackson-module-kotlin")
	testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
	testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll("-Xjsr305=strict", "-Xannotation-default-target=param-property")
	}
}

graalvmNative {
	// The reachability-metadata repository rejects this GraalVM release
	// (25.0.1, very recent LTS) on a schema-compatibility check, and pinning
	// an explicit version fails to download. Disabled here; the reflection
	// hints it would have supplied for Hibernate/JBoss Logging's generated
	// typed-logger classes are instead hand-written in
	// src/main/resources/META-INF/native-image/id.archmage/dekaliber/reflect-config.json
	// (generated by scanning hibernate-core/hibernate-validator for `*_$logger` classes).
	metadataRepository {
		enabled = false
	}
	agent {
        defaultMode = "standard"
    }
}

tasks.withType<Test> {
	useJUnitPlatform()
}
